#include "globals.h"
short filter1Even[LENGTH_FILTER1_HALF] = FILTER1_EVEN;
short filter1Odd[LENGTH_FILTER1_HALF] = FILTER1_ODD;
short filter2Even[LENGTH_FILTER2_HALF] = FILTER2_EVEN;
short filter2Odd[LENGTH_FILTER2_HALF] = FILTER2_ODD;
short filter3Even[LENGTH_FILTER2_HALF] = FILTER3_EVEN;
short filter3Odd[LENGTH_FILTER2_HALF] = FILTER3_ODD;